# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box
	config.vm.provider
	config.vm.network
	config.vm.synced_folder
	config.v.provision ='Apache,PHP,MySQL'

end